// ============================================================
// Solar-Grow - Modelo de Tarea
// ============================================================

/// Modelo que representa una tarea de cuidado de planta
class TaskModel {
  final int id;
  final int plantId;
  final String? plantName;
  final String? plantImage;
  final String? plantLocation;
  final String taskType;
  final String status;
  final String? description;
  final DateTime dueDate;
  final DateTime? completedAt;
  final int daysOverdue;
  final bool isAutoGenerated;
  final DateTime createdAt;

  TaskModel({
    required this.id,
    required this.plantId,
    this.plantName,
    this.plantImage,
    this.plantLocation,
    required this.taskType,
    required this.status,
    this.description,
    required this.dueDate,
    this.completedAt,
    this.daysOverdue = 0,
    this.isAutoGenerated = false,
    required this.createdAt,
  });

  /// Indica si la tarea está atrasada
  bool get isOverdue => daysOverdue > 0 || status == 'Atrasada';

  /// Indica si está completada
  bool get isCompleted => status == 'Completada';

  /// Ícono correspondiente al tipo de tarea
  String get taskIcon {
    switch (taskType) {
      case 'Regar':
        return '💧';
      case 'Fertilizar':
        return '🧪';
      case 'Trasplantar':
        return '🌱';
      case 'Podar':
        return '✂️';
      default:
        return '🔍';
    }
  }

  factory TaskModel.fromJson(Map<String, dynamic> json) {
    return TaskModel(
      id: json['id'],
      plantId: json['plant_id'],
      plantName: json['plant_name'],
      plantImage: json['plant_image'],
      plantLocation: json['plant_location'],
      taskType: json['task_type'],
      status: json['status'],
      description: json['description'],
      dueDate: DateTime.parse(json['due_date']),
      completedAt: json['completed_at'] != null
          ? DateTime.parse(json['completed_at'])
          : null,
      daysOverdue: json['days_overdue'] ?? 0,
      isAutoGenerated: json['is_auto_generated'] ?? false,
      createdAt: DateTime.parse(json['created_at']),
    );
  }
}
