// ============================================================
// Solar-Grow - Provider de Tareas
// ============================================================
import 'package:flutter/material.dart';
import '../models/task_model.dart';
import '../services/api_service.dart';
import '../config/api_constants.dart';

/// Provider que gestiona las tareas de cuidado de plantas
class TaskProvider extends ChangeNotifier {
  List<TaskModel> _todayTasks = [];
  List<TaskModel> _upcomingTasks = [];
  bool _isLoading = false;

  List<TaskModel> get todayTasks => _todayTasks;
  List<TaskModel> get upcomingTasks => _upcomingTasks;
  bool get isLoading => _isLoading;

  /// Cantidad total de tareas pendientes
  int get pendingCount => _todayTasks.where((t) => !t.isCompleted).length;

  /// Tareas agrupadas por tipo
  Map<String, List<TaskModel>> get tasksByType {
    final map = <String, List<TaskModel>>{};
    for (final task in _todayTasks) {
      map.putIfAbsent(task.taskType, () => []);
      map[task.taskType]!.add(task);
    }
    return map;
  }

  /// Cargar tareas de hoy
  Future<void> loadTodayTasks() async {
    _isLoading = true;
    notifyListeners();

    try {
      final data = await ApiService.get(
        ApiConstants.tasks,
        queryParams: {'upcoming': 'false'},
      );
      _todayTasks = (data as List).map((t) => TaskModel.fromJson(t)).toList();
    } catch (e) {
      _loadDemoTasks();
    }

    _isLoading = false;
    notifyListeners();
  }

  /// Cargar tareas próximas
  Future<void> loadUpcomingTasks() async {
    try {
      final data = await ApiService.get(
        ApiConstants.tasks,
        queryParams: {'upcoming': 'true'},
      );
      _upcomingTasks = (data as List)
          .map((t) => TaskModel.fromJson(t))
          .toList();
    } catch (e) {
      // Sin datos demo para próximas
    }
    notifyListeners();
  }

  /// Completar una tarea
  Future<bool> completeTask(int taskId) async {
    try {
      await ApiService.patch(
        '${ApiConstants.tasks}/$taskId',
        body: {'status': 'Completada'},
      );
      // Actualizar la lista local
      _todayTasks = _todayTasks.map((t) {
        if (t.id == taskId) {
          return TaskModel(
            id: t.id,
            plantId: t.plantId,
            plantName: t.plantName,
            plantImage: t.plantImage,
            plantLocation: t.plantLocation,
            taskType: t.taskType,
            status: 'Completada',
            description: t.description,
            dueDate: t.dueDate,
            completedAt: DateTime.now(),
            daysOverdue: t.daysOverdue,
            isAutoGenerated: t.isAutoGenerated,
            createdAt: t.createdAt,
          );
        }
        return t;
      }).toList();
      notifyListeners();
      return true;
    } catch (e) {
      return false;
    }
  }

  /// Datos de demo
  void _loadDemoTasks() {
    final now = DateTime.now();
    _todayTasks = [
      TaskModel(
        id: 1,
        plantId: 1,
        plantName: 'Echeveria',
        plantLocation: 'Balcon',
        taskType: 'Regar',
        status: 'Pendiente',
        dueDate: now,
        daysOverdue: 0,
        isAutoGenerated: true,
        createdAt: now.subtract(const Duration(hours: 2)),
      ),
      TaskModel(
        id: 2,
        plantId: 2,
        plantName: 'Áloe de arena',
        plantLocation: 'Dormitorio',
        taskType: 'Regar',
        status: 'Atrasada',
        dueDate: now.subtract(const Duration(days: 1)),
        daysOverdue: 1,
        isAutoGenerated: true,
        createdAt: now.subtract(const Duration(days: 2)),
      ),
      TaskModel(
        id: 3,
        plantId: 2,
        plantName: 'Áloe de arena',
        plantLocation: 'Dormitorio',
        taskType: 'Fertilizar',
        status: 'Atrasada',
        dueDate: now.subtract(const Duration(days: 2)),
        daysOverdue: 2,
        isAutoGenerated: true,
        createdAt: now.subtract(const Duration(days: 3)),
      ),
      TaskModel(
        id: 4,
        plantId: 1,
        plantName: 'Echeveria',
        plantLocation: 'Balcon',
        taskType: 'Trasplantar',
        status: 'Atrasada',
        dueDate: now.subtract(const Duration(days: 1)),
        daysOverdue: 1,
        isAutoGenerated: true,
        createdAt: now.subtract(const Duration(days: 3)),
      ),
      TaskModel(
        id: 5,
        plantId: 2,
        plantName: 'Áloe de arena',
        plantLocation: 'Balcon',
        taskType: 'Trasplantar',
        status: 'Atrasada',
        dueDate: now.subtract(const Duration(days: 2)),
        daysOverdue: 2,
        isAutoGenerated: true,
        createdAt: now.subtract(const Duration(days: 4)),
      ),
    ];
  }
}
